import React from "react";
import { View, Text } from "@react-pdf/renderer";
import { ReportMeta } from "../../types";
import { pdfStyles } from "./styles";

interface PdfFooterProps {
    meta: ReportMeta;
}

export const PdfFooter: React.FC<PdfFooterProps> = ({ meta }) => {
    return (
        <View style={pdfStyles.footer}>
            <Text>{meta.generatedBy ? `Generated by ${meta.generatedBy}` : "System Generated"}</Text>
            <Text>Target: {meta.period || meta.reportDate}</Text>
            <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
    );
};
